# This is a basic workflow to help you get started with Actions

name: update-releases

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update releases
        run: ./update.sh

      - name: Commit changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .releases
          git commit -m "update $GITHUB_RUN_NUMBER on $(date --iso-8601=date)"
          git push origin $GITHUB_REF_NAME
          
